### ISSUE TITLE
Exception not caught while working with value which may be not a string

### ISSUE THREAD

**Issue by gvidon** [okfn/jsontableschema-py#16]
```re.sub``` will throw exception which will not be caught — https://github.com/okfn/jtskit-py/blob/master/jtskit/_types.py#L156

**Comment by pwalsh** [comment]
@gvidon thanks. Can you make this fix, and add a test to prove it, as part of the current work you are doing to port JTSKit to Javascript.

**Comment by pwalsh** [comment]
Closing in favor of https://github.com/okfn/jsontableschema-py/issues/26
