### ISSUE TITLE
Consistent type casting interface

### ISSUE THREAD

**Issue by pwalsh** [okfn/jsontableschema-py#17]
cc @gvidon

When we cast, we return False if the value cannot be cast to the type / format.

When the value can be cast, we sometimes return True, and sometimes the value as cast (which is truthy).

We need to be consistent. We can't always return the value as cast, as this could sometimes be falsy - eg: empty string, midnight, null type/none

So, we need to do the following:

* Always return True of False from any cast_ method
* Add another method, something like `get_cast`, to return the value as cast

**Comment by pwalsh** [comment]
this issue is also relevant for https://github.com/okfn/json-table-schema-js

**Comment by pudo** [comment]
FYI, I've started packaging the ``messytables`` type conversion code as a separate package, [typecast](https://github.com/pudo/typecast). Might be useful here, too.

**Comment by pwalsh** [comment]
@pudo 

Are you willing to add JTS-specific stuff into typecast?

Specifically:

* The interplay of `type` and `format`
  * eg: [binary format for strings](https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/types.py#L127)
  * eg: [any format for dates](https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/types.py#L280)
* More complex types (arrays, geojson, etc.)
* Reference fields (also not yet implemented in jsontableschema)

If yes, I'd be happy to port parts of `jsontableschema` over with the goal of delegating `jsontableschema.types` to `typecast`.

**Comment by pudo** [comment]
Sounds great! The binary thing seems reasonable and easy to do; I'd just leave the purely validation-style formats (uri, email) to another tool - what do you think?

As for dates, my problem is that we're trying to do too much and there must be a smarter approach. Right now, typecast tests for about 300 formats which are generated from patterns, and it's really slow even after I started compiling them into regexen. 

I'll just give you write on the repo and we can see how it goes!

**Comment by pwalsh** [comment]
As far as JTS + date types is concerned, we either require an explicit format, which is fast, or `any` in which case I'm happy to take the performance hit in order to provide flexibility.

Leaving validation-style formats **out** of `typecast` is ok, but it just means that `typecast` will never natively support JSON Table Schema or JSON Schema, each of which have "primitive types" and "validation formats". 

I think we'd end up with an unclear API if we don't have consistency here: either `typecast` itself supports (all) such `formats` for JSON Table Schema and JSON Schema, or, higher level type cast libraries do.

**Comment by pudo** [comment]
Re dates: of course, if you have an explicit format it's really fast. 

Re validation-style formats: hm, good point. Maybe typecast should support them What worries me about implementing them is that they're modular in JSON Schema, so you're stuck implementing [a plugin mechanism](https://github.com/Julian/jsonschema/blob/master/jsonschema/_format.py#L38) for format validators... Do you think just supporting a few common ones (like URI, email, IPv4/6) would be a workable compromise?

**Comment by pwalsh** [comment]
I think we could support a few common ones, but `typecast` should still have a clear API for "primitive type" and "validation format" for each type (or as you call it, converter) class it implements. That will make implementing higher level typecast libs easier/consistent. WDYT?

The bottom line is though, that in this case `typecast` will never itself fully support JSON Schema or JSON Table Schema - that sounds totally ok, BTW, I'm just pointing that out.

**Comment by pudo** [comment]
Ok, that makes sense! And yes, it shouldn't support these schema types - just per-field conversions. Let's get hacking :)

**Comment by pwalsh** [comment]
So, similar to how I have here `self.py` for type, `self.format` for (optional) format, and `self.formats` which is a tuple of supported formats, `typecast` will have `self.result_type` and (optional) `self.result_format`, as well as a tuple of supported `self.result_formats`.

**Comment by pwalsh** [comment]
Hey @pudo 

So, I haven't had much time for coding :). But I'm probably going to get someone to work on this. Thinking to follow this pattern:

1. Update the type casting interface following the `typecast` API (test/cast), which mostly solves the issue in this ticket anyway
2. Then, once we have updated the API, use it as a proposed implementation for typecast, to drop some stuff directly into there, and depend on it here, as stated above.

FYI

**Comment by pwalsh** [comment]
Closing in favor of https://github.com/okfn/jsontableschema-py/issues/26 for implementation.
