### ISSUE TITLE
Can't install jsontableschema from pip

### ISSUE THREAD

**Issue by femtotrader** [okfn/jsontableschema-py#21]
Hello,

    $ pip install jsontableschema
    Collecting jsontableschema
      Could not find a version that satisfies the requirement jsontableschema (from versions: )
    No matching distribution found for jsontableschema

I'm using Mac OS X under Anaconda 3

    $ pip install git+https://github.com/okfn/jsontableschema-py

works fine

Kind regards

**Comment by pwalsh** [comment]
Hmm, sorry. I've updated the code here, and the readme, but I haven't published to pypi. I'll do so soon, with proper change logs, semver, etc. Meanwhile, do `pip install jtskit`, and the CLI is `jstkit`.

Sorry for the hassle.

**Comment by pwalsh** [comment]
As per https://github.com/okfn/jsontableschema-py/issues/22
