### ISSUE TITLE
cannot import name 'JSONTableSchema'

### ISSUE THREAD

**Issue by femtotrader** [okfn/jsontableschema-py#22]
Hello,

    from jsontableschema.models import JSONTableSchema

raises

    ImportError                               Traceback (most recent call last)
    <ipython-input-4-a5e48c1088d3> in <module>()
    ----> 1 from jsontableschema.models import JSONTableSchema

    ImportError: cannot import name 'JSONTableSchema'

Any idea ?

Kind regards

**Comment by femtotrader** [comment]
I think it should be

    from jsontableschema.models import SchemaModel

**Comment by femtotrader** [comment]
so https://github.com/okfn/jsontableschema-py/blob/master/README.md should be changed accordingly

**Comment by pwalsh** [comment]
Hi, yes, sorry about that. I need to setup a `develop` and keep `master` as a stable branch. I started a transition to rename this to `jsontableschema` (it is currently on PyPI as `jtskit`) and clean up the API a bit, but I did not finish this work.

**Comment by pwalsh** [comment]
I'm closing this: `jtskit` from PyPI works; and the current state here is "under development". We'll push a new release to PyPI as soon as we can.
