### ISSUE TITLE
Convert JSON Table Schema to DataShape

### ISSUE THREAD

**Issue by femtotrader** [okfn/jsontableschema-py#23]
From https://github.com/trickvi/datapackage/issues/60

Hello,

I wonder if any work has been done to convert JSON Table Schema to DataShape.
http://odo.pydata.org/en/latest/datashape.html
http://datashape.pydata.org/

It will greatly help to make DataPackages "odo"-izable
https://github.com/blaze/odo/issues/317

Kind regards

**Comment by pwalsh** [comment]
I did not know odo. It looks very useful.

JTS > DataShape should be quite straight forward. I'd recommend a standalone lib, as we do with [`jts-sql`](https://github.com/okfn/jts-sql). Would you be interested in hacking on a `jts-datashape` lib? If yes, I can start a new repo in the OKFN namespace, and you could make a start and we can help flesh it out.

**Comment by femtotrader** [comment]
Thanks but I don't think we need an other repository (it's hope to you).

`jsontableschema.models.SchemaModel` have `as_json` and `as_python` properties maybe a `as_datashape` property will be enough.

**Comment by pwalsh** [comment]
@femtotrader we like to keep our libraries modular. In the same way the we have not implemented `as_sql` in here, we likewise would not implement `as_datashape`.

That's just how we do things :). The main reasons for this approach are:

* Less monolithic codebases
* Fixes/refactors to specific implementations (such as `jts-sql`, `jts-datashape`) can be worked on without requiring a version bump or other general packaging updates on the core lib

**Comment by femtotrader** [comment]
ok. let's do a `jts-datashape` ;-)

**Comment by femtotrader** [comment]
We will need to build a dict which map JSON Table Schema types to DataShape types 

Here is DataShape types 
http://datashape.pydata.org/types.html#dtypes

I noticed that JTSKit type class are according
https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/types.py

    AnyType, StringType, BooleanType, NumberType, IntegerType, NullType,
    DateType, TimeType, DateTimeType, ArrayType, ObjectType,
    GeoPointType, GeoJSONType

A similar dict was made between JSON Table Schema type to JTSKit type class
https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/models.py


    @staticmethod
    def _type_map():
        """Map a JSON Table Schema type to a JTSKit type class."""

        return {
            'string': types.StringType,
            'number': types.NumberType,
            'integer': types.IntegerType,
            'boolean': types.BooleanType,
            'null': types.NullType,
            'array': types.ArrayType,
            'object': types.ObjectType,
            'date': types.DateType,
            'time': types.TimeType,
            'datetime': types.DateTimeType,
            'geopoint': types.GeoPointType,
            'geojson': types.GeoJSONType,
            'any': types.AnyType
        }

So I wonder if we should use JTSKit type as key or JSON Table Schema type ?

What is your opinion about it ?

**Comment by pwalsh** [comment]
@femtotrader 

So, just to make sure it is clear, this dict is just a mapping between types in the JSON Table Schema spec, and, classes that implement these types (and their associated formats from the spec) in Python, with methods to do stuff, etc.

So, from looking at the DataShape spec, you'll actually have to map from JTS "type/format/constraint" > DataShape "type".

* http://dataprotocols.org/json-table-schema/#field-types-and-formats
* http://dataprotocols.org/json-table-schema/#field-constraints

I'd say: first, let's forget about code and just work out what the mapping would actually have to be in order to got from jts > datashape, and vice versa.

I gave you access here: https://github.com/okfn/jts-datashape

**Comment by pwalsh** [comment]
https://github.com/okfn/jts-datashape
