### ISSUE TITLE
Remove dependency on rfc3987 (GPL)

### ISSUE THREAD

**Issue by David-Noble-at-work** [okfn/jsontableschema-py#36]
We'd like to consider using your jsontableschema-py package which is licensed under MIT, but cannot take a dependency on rfc3987 because it is distributed under GPL. I see that you use just one method from this package in just one place. I did not find a good alternative in a quick search of the internet, but your MIT license appears to be in conflict with GPL.

**Comment by pwalsh** [comment]
Hi @David-Noble-at-work thanks for flagging this. Yes, we certainly want to keep the library useful and usable for anyone who can't do GPL.

If you have any suggestions to replace this, we've be happy for a PR. Otherwise we will try to look at it at next available opportunity.

@joetsoi do you know of any MIT-licensed alternatives to this package?

**Comment by David-Noble-at-work** [comment]
Thanks. We've not got a replacement in mind, but will keep our eyes open for one.

On Nov 7, 2015, at 10:28 AM, Paul Walsh <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @David-Noble-at-work<https://github.com/David-Noble-at-work> thanks for flagging this. Yes, we certainly want to keep the library useful and usable for anyone who can't do GPL.

If you have any suggestions to replace this, we've be happy for a PR. Otherwise we will try to look at it at next available opportunity.

@joetsoi<https://github.com/joetsoi> do you know of any MIT-licensed alternatives to this package?

**Comment by shakeelmohamed** [comment]
Hi @pwalsh,

The [rfc3986](https://github.com/sigmavirus24/rfc3986) library is Apache 2.0. In the [docs](https://rfc3986.readthedocs.org/en/latest/#alternatives) they mention rfc3987 as an alternative. They also mention [utitools](https://github.com/tkem/uritools) which is MIT licensed, but does not provide validation.

**Comment by pwalsh** [comment]
# Tasks

* [ ] Remove dependency on rfc3987, replacing with reasonable alternative that is not *GPL licensed
* [ ] Ensure tests pass

**Comment by shakeelmohamed** [comment]
We appreciate your responsiveness @pwalsh, let me know if I can help :clap:
