### ISSUE TITLE
Why field is required by default?

### ISSUE THREAD

**Issue by roll** [okfn/jsontableschema-py#44]
May be it's more question for https://github.com/dataprotocols/dataprotocols/issues discussion. But http://dataprotocols.org/json-table-schema/index.html doesn't say `fields[].constraints.required` is `true` by default. It more sounds like it could be an additional constraint like other constraints. 

It's required by default here:
https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/model.py#L42-L46

**Comment by pwalsh** [comment]
@roll looks like I never made the PR to add this explicitly to the spec: https://github.com/dataprotocols/dataprotocols/issues/167
